### ISSUE TITLE
Generalize tags, make all strings use text_content

### ISSUE THREAD

**Issue by davepagurek** [emerald-lang/emerald#20]
Right now only certain tags allow having a string following it (heading tags.) Technically, we should be allowed to add text content in _any_ tag in the grammar, and we can optionally do semantics checking after parsing (e.g. if you add text content in an image tag or something.) Same for nesting. I think a good way to do this is to make a tag generic in the grammar and move the specific tag types into a stage after the grammar.

Also, in doing this, we should make all strings use the text_content grammar node so that any form of text can have variable templating.

**Comment by armcburney** [comment]
Closing this since #30 addressed this issue.
