### ISSUE TITLE
Proposal: Different types of string literals

### ISSUE THREAD

**Issue by davepagurek** [emerald-lang/emerald#21]
What are your thoughts different types of string literals?

```
p ->
  Hello, |name|
```
would become
```
<p>Hello, Dave</p>
```

and with a fat arrow:
```
p =>
  Hello, |name|
```
could have no interpolation and output:
```
<p>Hello, |name|</p>
```

This would give people a way to put text on the next line if it gets too long and still have interpolation, and a way to have a script or code tag without interpolation.

**Comment by davepagurek** [comment]
If `=>` and `->` are too similar to be distinguishable at first (I know I found that issue when learning Coffeescript at Shopify), we can maybe use `==` for the non-interpolated literals. The logic being, `==` is exactly equal to what gets outputted, `->` represents the transformation that gets applied.

**Comment by armcburney** [comment]
I think that's a fantastic suggestion! And I like the idea of using `=>` and `->`, I don't think we necessarily need to have a `==` for the non-interpolated literals, although semantically it makes more sense.

I'm on the fence about the symbols for non-interpolated literals - I think I'd be fine either way, but I definitely thing this is a good feature to have.
