### ISSUE TITLE
Create website for Emerald, in Emerald

### ISSUE THREAD

**Issue by davepagurek** [emerald-lang/emerald#24]
got to eat our own dog food 🐕

**Comment by armcburney** [comment]
I kinda started this a bit, but this was before a lot of the most recent changes: https://github.com/emerald-lang/website. I was thinking of doing the backend with sinatra - but that would probably entail us writing a gem like haml (https://rubygems.org/gems/haml/versions/4.0.7) where we can say:

```
# Haml
get '/' do
  haml :index, :format => :html5
end

# Emerald
get '/' do
  emerald :index
end
```

**Comment by armcburney** [comment]
One of the things we'll have to decide is how to make emerald fit in with existing technologies (such as Sinatra, Flask, Rails, Express), how to use it with backend languages (Go, Python, Ruby, Node, etc.), and automated build tools and task runners (like Grunt & Gulp).

We'll probably have to make a bunch of packages (npm, pip, ruby gems, etc.) which can let us use it for multiple languages and tools.

Thoughts?

**Comment by armcburney** [comment]
Closing this issue, we have a website made in Emerald here: https://emerald-lang.github.io/website/
