### ISSUE TITLE
Escape braces in preprocessor, and un-escape them in the code generation phase.

### ISSUE THREAD

**Issue by armcburney** [emerald-lang/emerald#9]
In the context free grammar, we use braces to signify indentation. The preprocessor adds braces based on the indentation level for emerald code. Hence, this code snippet

```
section
  div
    h1 This is a header.
```

becomes:

```
section
{
div
{
h1 This is a header.
}
}
```

We need to escape braces before preprocessing the emerald code, and unescape them when compiling in the code generation phase.

Ex.

```
html
  head
    script
      function sample_function() {
        console.log("Escape the braces please!");
      }
```

The braces in the script do not signify indentation, and should be escaped to avoid errors when being parsed by the context free grammar.

**Comment by davepagurek** [comment]
Turns out we don't need to escape them in literals. In inline literals we read to the end of the line, gobbling up any braces it encounters. Same goes for multiline literals, where we read all the way to a `$`.

**Comment by armcburney** [comment]
Nice! That's awesome!
